[package]
name = "migrator"
version = "0.1.2"
edition = "2021"

[dependencies]
postgres = "0.19"
chrono = "0.4"
regex = "*"
anyhow = "1.0"
clap = { version = "*", features = ["derive", "env"] }

[dev-dependencies]
serial_test = "*"
