services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: migrator-dev
    container_name: migrator-dev
    depends_on:
      - db
    environment:
      - PG_URL=postgres://experiment_user:asdf@db:5432/experiment-db?sslmode=disable
    volumes:
      - .:/usr/working/
    command: tail -F anything

  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_DB=experiment-db
      - POSTGRES_USER=experiment_user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    command: postgres -c 'max_wal_size=2GB'
